export { default as AddIcon } from './add-icon';
export { default as AvailabilityIcon } from './availability-icon';
export { default as BookingIcon } from './booking-icon';
export { default as BookingNumIcon } from './booking-num-icon';
export { default as CalendarsIcon } from './calendars-icon';
export { default as CopyWhiteIcon } from './copy-white-icon';
export { default as CalendarAddIcon } from './calender-add-icon';
export { default as CloneIcon } from './clone-icon';
export { default as DateIcon } from './date-icon';
export { default as DisableIcon } from './disable-icon';
export { default as EditIcon } from './edit-icon';
export { default as EmbedCodeIcon } from './embed-code-icon';
export { default as HelpIcon } from './help-icon';
export { default as HomeIcon } from './home-icon';
export { default as LinkIcon } from './link-icon';
export { default as LocationIcon } from './location-icon';
export { default as LogoIcon } from './logo';
export { default as LogoutIcon } from './logout-icon';
export { default as PeopleFillIcon } from './people-fill-icon';
export { default as PeopleWhiteIcon } from './people-white-icon';
export { default as PopUpIcon } from './pop-up-icon';
export { default as PriceIcon } from './price-icon';
export { default as ProfileIcon } from './profile-icon';
export { default as QrIcon } from './qr-icon';
export { default as SearchIcon } from './search-icon';
export { default as ShareEventIcon } from './share-event-icon';
export { default as ShareIcon } from './share-icon';
export { default as ShortCodeIcon } from './short-code-icon';
export { default as SortIcon } from './sort-icon';
export { default as SettingsIcon } from './settings-icon';
export { default as TrashIcon } from './trash-icon';
export { default as TrashRedIcon } from './trash-red-icon';
export { default as ToggleIcon } from './toggle-icon';
export { default as TimeIcon } from './time-icon';
export { default as UpgradeIcon } from './upgrade-icon';
export { default as AllCalendarIcon } from './all-calendar-icon';
export { default as CancelledCalendarIcon } from './cancelled-calendar-icon';
export { default as CompletedCalendarIcon } from './completed-calendar-icon';
export { default as LatestCalendarIcon } from './latest-calendar-icon';
export { default as PendingCalendarIcon } from './pending-calendar-icon';
export { default as UpcompingCalendarIcon } from './upcomping-calendar-icon';
export { default as SquareEditIcon } from './square-edit-icon';
export { default as ClockIcon } from './clock-icon';
export { default as AttendeeIcon } from './attendee-icon';
export { default as AddCalendarOutlinedIcon } from './add-calendar-outlined-icon';
export { default as CancelIcon } from './cancel-icon';
export { default as EmailConfirmIcon } from './email-confirm-icon';
export { default as MarkIcon } from './mark-icon';
export { default as RebookIcon } from './rebook-icon';
export { default as ResechduleIcon } from './resechedule-icon';
export { default as CalendarInformationIcon } from './calendar-information-icon';
export { default as TeamOutlinedIcon } from './team-outlined-icon';
export { default as TimezoneIcon } from './timezone-icon';
export { default as EmailIcon } from './email-icon';
export { default as CompassIcon } from './compass-icon';
export { default as SuccesIcon } from './success-icon';
export { default as FailIcon } from './fail-icon';
export { default as HostIcon } from './host-icon';
export { default as StatusIcon } from './status-icon';
export { default as QuestionOutlineIcon } from './question-outline-icon';
export { default as QuestionIcon } from './question-icon';
export { default as CalendarNoshowIcon } from './calendar-noshow-icon';
export { default as EmailNotiIcon } from "./email-noti-icon";
export { default as SmsNotiIcon } from "./sms-noti-icon";
export { default as WebhookIcon } from "./webhook-icon";
export { default as IntegrationsIcon } from "./integrations-icon";
export {default as PaymentIcon} from "./payment-icon";
export {default as EventLocIcon} from "./event-location-icon";
export {default as CalendarTickIcon} from "./calendar-tick-icon";
export {default as CalendarDeleteIcon} from "./calendar-delete-icon";
export {default as CalendarDisableIcon} from "./calendar-disable-icon";
export {default as AdvancedSettingsIcon} from "./advanced-settings-icon";
export {default as UrlIcon} from "./url-icon";
