name: WordPress and React Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

  workflow_dispatch:

jobs:
  php-test:
    name: WP ${{ matrix.wordpress }} on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 8.0, 8.1, 8.2]
        wordpress: [latest, "6.4", "6.3", "6.2", "6.1", "6.0", "5.9"]
        exclude:
          # WordPress 5.9 doesn't fully support PHP 8.1 and 8.2
          - php: 8.1
            wordpress: "5.9"
          - php: 8.2
            wordpress: "5.9"
          # PHP 8.2 compatibility is only fully supported in WP 6.2+
          - php: 8.2
            wordpress: "6.0"
          - php: 8.2
            wordpress: "6.1"

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SVN
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
          tools: composer
        
      - name: Remove incompatible dependencies for PHP < 8.1
        if: matrix.php < 8.1
        run: |
          composer remove --dev spatie/phpunit-watcher --no-update --no-interaction

      - name: Update Composer dependencies
        run: composer update --no-progress --no-ansi --no-interaction

      - name: Initialize MySQL Database
        run: |
          # Setup database permissions
          mysql -uroot -ppassword -e "CREATE DATABASE IF NOT EXISTS wordpress_test;"
          mysql -uroot -ppassword -e "GRANT ALL PRIVILEGES ON wordpress_test.* TO 'root'@'localhost';"
          mysql -uroot -ppassword -e "FLUSH PRIVILEGES;"
          
      - name: Set up WordPress test environment
        env:
          WP_TESTS_DB_NAME: wordpress_test
          WP_TESTS_DB_USER: root
          WP_TESTS_DB_PASSWORD: password
          WP_TESTS_DB_HOST: localhost
          WP_VERSION: ${{ matrix.wordpress }}
        run: |
          # Explicitly create test directory structure if needed
          mkdir -p /tmp/wordpress-tests-lib
          mkdir -p /tmp/wordpress
          
          # Run the WordPress test setup script
          bash bin/install-wp-tests.sh || { echo "WordPress test setup failed"; cat /tmp/wordpress-tests-lib/wp-tests-config.php; exit 1; }

      - name: Run PHPUnit tests
        env:
          WP_TESTS_DB_NAME: wordpress_test
          WP_TESTS_DB_USER: root
          WP_TESTS_DB_PASSWORD: password
          WP_TESTS_DB_HOST: localhost
        run: |
          echo "WordPress config:"
          cat /tmp/wordpress-tests-lib/wp-tests-config.php
          echo "Testing MySQL connection:"
          mysql --user=$WP_TESTS_DB_USER --password=$WP_TESTS_DB_PASSWORD --host=$WP_TESTS_DB_HOST -e "SHOW DATABASES;" || echo "MySQL connection failed"
          
          # Create an additional test symlink if needed
          if [ ! -d "/tmp/wordpress-tests-lib" ]; then
            echo "WordPress test directory not found"
            exit 1
          fi
          
          composer test
          
  react-test:
    name: React Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run React tests
        run: npm test 