name: WordPress and React Tests

on:

  workflow_dispatch:

jobs:
  php-test:
    name: WP ${{ matrix.wordpress }} on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 8.0, 8.1, 8.2]
        wordpress: [latest, "6.4", "6.3", "6.2", "6.1", "6.0", "5.9"]
        exclude:
          # WordPress 5.9 doesn't fully support PHP 8.1 and 8.2
          - php: 8.1
            wordpress: "5.9"
          - php: 8.2
            wordpress: "5.9"
          # PHP 8.2 compatibility is only fully supported in WP 6.2+
          - php: 8.2
            wordpress: "6.0"
          - php: 8.2
            wordpress: "6.1"

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SVN
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
          tools: composer
        
      - name: Remove incompatible dependencies for PHP < 8.1
        if: matrix.php < 8.1
        run: |
          composer remove --dev spatie/phpunit-watcher --no-update --no-interaction

      - name: Update Composer dependencies
        run: composer update --no-progress --no-ansi --no-interaction

      - name: Set up WordPress test environment
        env:
          WP_TESTS_DB_NAME: wordpress_test
          WP_TESTS_DB_USER: root
          WP_TESTS_DB_PASSWORD: password
          WP_TESTS_DB_HOST: 127.0.0.1
        run: |
          bash bin/install-wp-tests.sh

      - name: Run PHPUnit tests
        run: |
          composer test
          
  react-test:
    name: React Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run React tests
        run: npm test 
        
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [php-test, react-test]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: wordpress
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
      wordpress:
        image: wordpress:latest
        env:
          WORDPRESS_DB_HOST: 127.0.0.1
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: password
          WORDPRESS_DB_NAME: wordpress
          WORDPRESS_DEBUG: 1
        ports:
          - 8080:80
        options: --health-cmd="curl -f http://localhost:80/" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
          tools: composer
          
      - name: Install WordPress CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp
          
      - name: Install dependencies
        run: composer update --no-progress --no-ansi --no-interaction
        
      - name: Install plugin into WordPress
        run: |
          # Wait for WordPress to be ready
          sleep 10
          
          # Create WordPress directory
          mkdir -p /tmp/wordpress
          cd /tmp/wordpress
          
          # Download and configure WordPress
          wp core download --allow-root
          wp config create --dbname=wordpress --dbuser=root --dbpass=password --dbhost=127.0.0.1 --allow-root
          wp core install --url=localhost --title="Test Site" --admin_user=admin --admin_password=password --admin_email=test@example.com --skip-email --allow-root
          
          # Create plugin directory
          mkdir -p /tmp/wordpress/wp-content/plugins/quill-booking
          
          # Copy plugin files
          cp -r ${GITHUB_WORKSPACE}/* /tmp/wordpress/wp-content/plugins/quill-booking/
          
          # Install and activate plugin using WP-CLI
          cd /tmp/wordpress
          wp plugin activate quill-booking --allow-root
        
      - name: Run integration tests
        run: |
          composer run test:integration